#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef unsigned int uint;
typedef unsigned long long int uintll;

typedef uint8_t   u8;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint64_t u64;

// TODO:
#if 1
#define BE64 __builtin_bswap64
#else
#define BE64
#endif

#define ASSERT(c) ({ if (!(c)) abort(); })

#define BUILD_ASSERT(c) _Static_assert(c, #c)

// __attribute__((target("popcnt", "avx2")))

#ifndef XHASH_BITS
#define XHASH_BITS 512
#error "XHASH_BITS IS NOT SET"
#endif

#if XHASH_BITS == 512
typedef u64 u64x8  __attribute__ ((vector_size( 8 * sizeof(u64)))); 
typedef u32 u32x16 __attribute__ ((vector_size(16 * sizeof(u32))));
typedef u16 u16x32 __attribute__ ((vector_size(32 * sizeof(u16))));
typedef u8  u8x64  __attribute__ ((vector_size(64 * sizeof(u8))));
#elif XHASH_BITS == 256
typedef u64 u64x4  __attribute__ ((vector_size( 4 * sizeof(u64))));
typedef u32 u32x8  __attribute__ ((vector_size( 8 * sizeof(u32))));
typedef u16 u16x16 __attribute__ ((vector_size(16 * sizeof(u16))));
typedef u8  u8x32  __attribute__ ((vector_size(32 * sizeof(u8))));
#elif XHASH_BITS == 128
typedef u64 u64x2  __attribute__ ((vector_size( 2 * sizeof(u64))));
typedef u32 u32x4  __attribute__ ((vector_size( 4 * sizeof(u32))));
typedef u16 u16x8  __attribute__ ((vector_size( 8 * sizeof(u16))));
typedef u8  u8x16  __attribute__ ((vector_size(16 * sizeof(u8))));
#else
#error
#endif

#define X_LEN 8

#if defined(__clang__)
#define __optimize // TODO:
#define __builtin_shuffle __builtin_shufflevector
#else
#define __optimize __attribute__((optimize("-O3", "-ffast-math", "-fstrict-aliasing")))
#endif

#if XHASH_BITS == 512
typedef u64x8 xhash_t;
typedef u8x64 xhash_bytes_t;
#elif XHASH_BITS == 256
typedef u64x4 xhash_t;
typedef u8x32 xhash_bytes_t;
#elif XHASH_BITS == 128
typedef u64x2 xhash_t;
typedef u8x16 xhash_bytes_t;
#endif

//
BUILD_ASSERT(sizeof(xhash_t)
          == sizeof(xhash_bytes_t));

// OFFSET OF THE SIZE VALUE
#define _XHASH_TSIZE (sizeof(xhash_t) - 1)

typedef struct xhash_s {
    xhash_t X [X_LEN]; // SHUFFLER
    xhash_t A; // ACCUMULATOR
    u8 tmp [sizeof(xhash_t)];
    u8 pad [sizeof(xhash_t)]; // PADDING
} xhash_s;

#if XHASH_BITS == 512
#define __v_8(x0, x1, x2, x3, x4, x5, x6, x7) { x0, x1, x2, x3, x4, x5, x6, x7 }
#elif XHASH_BITS == 256
#define __v_8(x0, x1, x2, x3, x4, x5, x6, x7) { x0, x1, x2, x3 }
#elif XHASH_BITS == 128
#define __v_8(x0, x1, x2, x3, x4, x5, x6, x7) { x0, x1 }
#endif

#if XHASH_BITS == 512
#define __v_64(                                 \
        x00, x01, x02, x03, x04, x05, x06, x07, \
        x08, x09, x10, x11, x12, x13, x14, x15, \
        x16, x17, x18, x19, x20, x21, x22, x23, \
        x24, x25, x26, x27, x28, x29, x30, x31, \
        x32, x33, x34, x35, x36, x37, x38, x39, \
        x40, x41, x42, x43, x44, x45, x46, x47, \
        x48, x49, x50, x51, x52, x53, x54, x55, \
        x56, x57, x58, x59, x60, x61, x62, x63  \
    ) {                                         \
        x00, x01, x02, x03, x04, x05, x06, x07, \
        x08, x09, x10, x11, x12, x13, x14, x15, \
        x16, x17, x18, x19, x20, x21, x22, x23, \
        x24, x25, x26, x27, x28, x29, x30, x31, \
        x32, x33, x34, x35, x36, x37, x38, x39, \
        x40, x41, x42, x43, x44, x45, x46, x47, \
        x48, x49, x50, x51, x52, x53, x54, x55, \
        x56, x57, x58, x59, x60, x61, x62, x63  \
    }
#elif XHASH_BITS == 256
#define __v_64(                                 \
        x00, x01, x02, x03, x04, x05, x06, x07, \
        x08, x09, x10, x11, x12, x13, x14, x15, \
        x16, x17, x18, x19, x20, x21, x22, x23, \
        x24, x25, x26, x27, x28, x29, x30, x31, \
        x32, x33, x34, x35, x36, x37, x38, x39, \
        x40, x41, x42, x43, x44, x45, x46, x47, \
        x48, x49, x50, x51, x52, x53, x54, x55, \
        x56, x57, x58, x59, x60, x61, x62, x63  \
    ) {                                         \
        x00, x01, x02, x03, x04, x05, x06, x07, \
        x08, x09, x10, x11, x12, x13, x14, x15, \
        x16, x17, x18, x19, x20, x21, x22, x23, \
        x24, x25, x26, x27, x28, x29, x30, x31  \
    }
#elif XHASH_BITS == 128
#define __v_64(                                 \
        x00, x01, x02, x03, x04, x05, x06, x07, \
        x08, x09, x10, x11, x12, x13, x14, x15, \
        x16, x17, x18, x19, x20, x21, x22, x23, \
        x24, x25, x26, x27, x28, x29, x30, x31, \
        x32, x33, x34, x35, x36, x37, x38, x39, \
        x40, x41, x42, x43, x44, x45, x46, x47, \
        x48, x49, x50, x51, x52, x53, x54, x55, \
        x56, x57, x58, x59, x60, x61, x62, x63  \
    ) {                                         \
        x00, x01, x02, x03, x04, x05, x06, x07, \
        x08, x09, x10, x11, x12, x13, x14, x15  \
    }
#endif

// TODO: PERMITIR INICIALIZAR OS PARAMETROS NO CREATE E NO RESET
static const xhash_s skel = {
    { // X
        __v_8 (
            0b1010100110100010111000110011111110110110000100111100011101011101ULL,
            0b1000011111001101001111010111101100100110100000100101101101100110ULL,
            0b0101010011001110100101010111001101010010010010111100111110001101ULL,
            0b0011011100110101101001110100010010001101001000110101100101001011ULL,
            0b0100110111110110010110101001011100101001010000011000101000000001ULL,
            0b0010000001101101010010111110100110110100100110100010100101111101ULL,
            0b0101111111000011011010001101110000100000010111001101100101000100ULL,
            0b1000001100100001101101111010011011011110000001001000101111000111ULL
        ), __v_8 (
            0b1111010001001011110111100001001111001110100100111100110110000000ULL,
            0b1000011110100111100010010111000000011111111000010101001010010101ULL,
            0b0001101011011111000100010000001110011001010110111011001010111010ULL,
            0b1010000110101100011101000110100111010001111101111100001011100110ULL,
            0b1011110111111110100100010110010101001100110100001010111101100000ULL,
            0b1101000011000100000111101001111100001101100100010100001100111111ULL,
            0b0101111110000001110001101100100110001100001001011101010001011000ULL,
            0b0100101011010001100100101010100011110011000101011101101110101100ULL
        ), __v_8 (
            0b0101000100101010010010100000011010101011000101111101111101001101ULL,
            0b0111010101001111000111111100110000101000000000010100101101011001ULL,
            0b1111011101010100010101101101101111101101110110110001000001001100ULL,
            0b1001100101111100010111110000101010111111011000111011000111010111ULL,
            0b0000010100010000011000010001000000000001111000011010110011010111ULL,
            0b1100001001110011100101011101111100000001000010010111110011110110ULL,
            0b1111000000111101110010111101111011011101110111010110100110101000ULL,
            0b0101010000101000100101100111110100011000001001101000011101100100ULL
        ), __v_8 (
            0b1110111000101100101010000100101011110010100010101100001110010010ULL,
            0b1111000111011101000111000110110000010011000110010010000101011101ULL,
            0b0001110000010011101110111100101110010001101001011110000101101010ULL,
            0b1000000101011011010000011011100101110011101010001000010001110101ULL,
            0b1000001010111110010010110011011110101010010010011101010101000100ULL,
            0b1100011111001001011101101001100111101010011010001010010110101001ULL,
            0b0011100011111000010011111000111110100000001111101110001011110110ULL,
            0b0001111101001110100000000111111010111101001100100101011110011001ULL
        ), __v_8 (
            0b1001111111010111101100101101110010110110101001010110010111101001ULL,
            0b0001000011011010011100000010101100001101111100111101010001001111ULL,
            0b0101010111111010001010111010000100011000100000001011100110111110ULL,
            0b1011101111001010000101110001100110001000001110101110100101100001ULL,
            0b1011000101100110111111001000100100101101011001100111010001110100ULL,
            0b1110110001110101110111111100111101101010010111001010110000010000ULL,
            0b0111111100000100100010011110101010000001100010000010000101100100ULL,
            0b0110111000001110011011101001101010000000000100001110011101111100ULL
        ), __v_8 (
            0b1010010010100011011110110001100101111000111000001001101110100101ULL,
            0b1111101001011111000110110010101100001101010011100010001110111111ULL,
            0b0111110100111111111011100000111001101001111100001010010110010001ULL,
            0b0101011000001001111011000011001110100100011110111110100111000000ULL,
            0b1010100111010101100000110110010100000101010110100001000001010010ULL,
            0b0001101001000011100000111111110101100000110100010011000011001100ULL,
            0b0101110111000110010011110000011111110001100010110010011011110100ULL,
            0b1011110111010110000001100101111000111010001111011000100010100001ULL
        ), __v_8 (
            0b0001111101101010110011000001110000110111010111000101010001111000ULL,
            0b1101110001001000110110001010111111101001111000100000110001101001ULL,
            0b0100001111011101010100110011111000100010111101111100000100111000ULL,
            0b0110111000000010000001100010011000010111010110110011111010100010ULL,
            0b1100011001000101001100010111011101000110110001010110100010011100ULL,
            0b1000011010000001101110010001101011001100111010111100100011010000ULL,
            0b0110010100111001110111111000010100001011010110010100011001110011ULL,
            0b1001111101100100111101111110001110110001110101001110101101110001ULL
        ), __v_8 (
            0b1111010101001001100101001100110011011000110010001101111011101111ULL,
            0b1001011100101110011001011111110001010010111111001000011010001011ULL,
            0b0010001111100011101011101100010011000110001001001000000000110101ULL,
            0b1001011000011011010011101011101010110001001010011000011111000010ULL,
            0b0000100101100110110101011011001101110001100100000111100011011101ULL,
            0b1101011001101001010001111010110001001110000101100000100111010110ULL,
            0b0011101111011100000101101100100010000001110010111010100011101111ULL,
            0b1111110100100001001101100010101110010100100000100101110011000111ULL
        )
    },

    __v_8 ( // A
            0b1111000000100001011100000000110010110000000100101101110111101101ULL,
            0b1101111001010101011010100011000101001110011101000101110000110101ULL,
            0b1001011111000010000000000110100111110111110011101100010110000110ULL,
            0b1011100000010111011100110100110100010110110110000101111111110010ULL,
            0b1101001010110010111110010101111111101011000010110110101110110010ULL,
            0b0000000110111001100011100011100110110110010011001110011000001010ULL,
            0b0001010111111000100111111000100111001011010000011000000111100101ULL,
            0b0010001110110011101110010101010000101001110100100111001110010010ULL
    ),

    // TEMP, TEMP SIZE
    { 0 },

    __v_64 ( // PAD
        0x0B, 0xE9, 0x10, 0x9F, 0xC5, 0xC0, 0x99, 0x1E,
        0xA7, 0xEE, 0x56, 0xBC, 0xA6, 0xA4, 0x6A, 0xB3,
        0xE5, 0x21, 0x41, 0xD7, 0x92, 0xE5, 0xA9, 0xFE,
        0xAD, 0xB0, 0xFB, 0x6C, 0xD3, 0x46, 0xC2, 0x88,
        0x17, 0x8F, 0x35, 0xD4, 0x14, 0xB0, 0xFD, 0xD9,
        0x79, 0x46, 0x7C, 0x8B, 0x22, 0x18, 0x21, 0x4D,
        0x43, 0x1C, 0x1F, 0x33, 0x75, 0xD2, 0x4F, 0xC7,
        0x2B, 0xE0, 0x2E, 0x20, 0x27, 0x8A, 0x6A, 0xDF
    )
};

// NOTE: THE HASH IS SAVED BIG ENDIAN
// TODO: restrict ctx vs ctx->temp?
// TODO: UMA VERSAO ALINHADA
static inline void __optimize xhash_do (xhash_s* const restrict ctx, const u8* restrict data, uint q) {

#define A (ctx->A)
#define X (ctx->X)

    while (q) {
           q--;

        // ORIGINAL
        xhash_t O; memcpy(&O, data, sizeof(xhash_t)); data += sizeof(xhash_t);

        //
        BUILD_ASSERT(sizeof(O) == sizeof(ctx->tmp));

        // LOCAL ENDIANESS
#if 1
        O = (xhash_t) __builtin_shuffle( (xhash_bytes_t) O,
            (xhash_bytes_t) ( (xhash_t) {
                0x0001020304050607ULL,
                0x08090A0B0C0D0E0FULL,
#if XHASH_BITS > 128
                0x1011121314151617ULL,
                0x18191A1B1C1D1E1FULL,
#if XHASH_BITS > 256
                0x2021222324252627ULL,
                0x28292A2B2C2D2E2FULL,
                0x3031323334353637ULL,
                0x38393A3B3C3D3E3FULL
#endif
#endif
            })
        );
#endif

        // ACCUMULATE AND MIX
        for (uint i = 0; i != X_LEN; i++) {

            xhash_t q = A + O;

            // YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
            //                         + >> 32 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            //                                 YYYYYYYYYYYYYYYYXXXXXXXXXXXXXXXX|
            //                         + >> 16                 YYYYYYYYYYYYYYYY|XXXXXXXXXXXXXXXX
            //                                                 YYYYYYYYXXXXXXXX|
            //                         + >>  8                         YYYYYYYY|XXXXXXXX
            //                                                         YYXXXXXX|
            //                         + >>  4                             YYXX|XXXX
            //                           &                               XXXXXX|
            q += q >> 32;
            q += q >> 16;
            q += q >>  8;
            q += q >>  4;

            q &= 0b111111U; // %= 64 BITS

            // SWAP64
            // O ORIGINAL NAO PERDE NENHUM BIT POIS NAO HA OVERFLOW
            A += O = (O >> q) | (O << (64 - q));

            //
            A += (xhash_t) __builtin_shuffle(
                 (xhash_bytes_t) (X[i]),
                ((xhash_bytes_t) A) & (sizeof(xhash_bytes_t) - 1)
            );

            // OPOSITE X
            // ESCOLHE UM VETOR
            // ESCOLHE AS PALAVRAS DESTE VETOR
            // TODO: ESSE BUILTIN_SHUFFLE RETORNA MESMO ESTE TIPO?
            // [ (i, (8 - 1) - i) for i in range(8) ]
            // [(0, 7), (1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1), (7, 0)]
            A += (xhash_t) __builtin_shuffle(
                 (xhash_bytes_t) (X[(X_LEN - 1) - i]),
                ((xhash_bytes_t) A) & (sizeof(xhash_bytes_t) - 1)
            );

            //
            A = X[i] += A;
        }
    }

#undef A
#undef B
}

void __optimize xhash_iter (xhash_s* const restrict ctx, const u8* restrict data, uint size) {

    // NOTE: É SAFE PASSAR DATA NULL COM SIZE 0
    ASSERT(data != NULL || size == 0);

    // QUANTO TEM
    uint tsize = ctx->tmp[_XHASH_TSIZE];

    if (tsize) {

        ASSERT(tsize <= _XHASH_TSIZE);

        // QUANTO FALTA PARA COMPLETAR
        uint puxar = sizeof(xhash_t) - tsize;

        // SÓ PODE PEGAR O QUE TEM
        if (puxar > size)
            puxar = size;

        memcpy(ctx->tmp + tsize, data, puxar);

        // TIROU DO BUFFER...
        data += puxar;
        size -= puxar;

        // ...E COLOCOU NO TEMP
        if ((tsize += puxar) != sizeof(xhash_t)) {
            // AINDA NAO TEM UM TEMP COMPLETO
            ASSERT(size == 0);
            ctx->tmp[_XHASH_TSIZE] = tsize;
            return;
        }

        xhash_do(ctx, ctx->tmp, 1);
    }

    // NAO TEM TEMP
    xhash_do(ctx, data, size / sizeof(xhash_t));

    // SOBROU ISSO
    if ((tsize = size % sizeof(xhash_t)))
        memcpy(ctx->tmp, data + size - tsize, tsize);

    ctx->tmp[_XHASH_TSIZE] = tsize;
}

void __optimize xhash_done (xhash_s* const restrict ctx, const u8* restrict data, uint size, u8* const restrict hash, const uint hash_len) {

    ASSERT(data != NULL || size == 0);
    ASSERT(hash != NULL || hash_len == 0);

    // ????????
    if (hash_len > (sizeof(xhash_t) * (X_LEN + 1)))
        // TODO: FAILED
        return;

    //
    xhash_iter(ctx, data, size);

    // NA VERDADE NÃO É SÓ UM PAD, VAI USAR ELE INTEIRO MESMO QUE NAO TENHA TEMP
    const uint tsize =        ctx->tmp[_XHASH_TSIZE];
    const uint psize = sizeof(ctx->tmp) - tsize;

    if (psize)
        memcpy(ctx->tmp + tsize,
               ctx->pad + tsize, psize);

    //
    xhash_do(ctx, ctx->tmp, 1);

    //
    ctx->tmp[_XHASH_TSIZE] = 0;

    //
    xhash_t result = ctx->A;

    // __builtin_rotateright

    // TODO: REDUCE ALL WORDS?

    // GLOBAL ENDIANESS
#if 1
    result = (xhash_t) __builtin_shuffle( (xhash_bytes_t) result,
        (xhash_bytes_t) ( (xhash_t) {
            0x0001020304050607ULL,
            0x08090A0B0C0D0E0FULL,
#if XHASH_BITS > 128
            0x1011121314151617ULL,
            0x18191A1B1C1D1E1FULL,
#if XHASH_BITS > 256
            0x2021222324252627ULL,
            0x28292A2B2C2D2E2FULL,
            0x3031323334353637ULL,
            0x38393A3B3C3D3E3FULL
#endif
#endif
        })
    );
#endif

    ASSERT(BE64(ctx->A[0]) == result[0]);
    ASSERT(BE64(ctx->A[1]) == result[1]);

    // SAVE
    memcpy(hash, &result, hash_len);
}

static xhash_s* xhash_new (void) {

    xhash_s* const ctx = aligned_alloc(sizeof(ctx->A), sizeof(xhash_s));

    if (ctx) {

        memcpy(ctx, &skel, sizeof(xhash_s));

        ASSERT(ctx->tmp[_XHASH_TSIZE] == 0);
    }

    return ctx;
}

static void xhash_free (xhash_s* const ctx) {

    free(ctx);
}

// FOR SPEED
// WE CAN ALWAYS DO A EVEN DEEPER CHECK BY VERIFYING THE HASH OF THE FILES
void __optimize xcsum (const void* restrict data, uint size, void* restrict csum);


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 18), // void()(xhash_s *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // xhash_s *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 18), // void()(xhash_s *, uint8_t const *, unsigned int)
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 17), // uint8_t const *
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8), // unsigned int
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 18), // void()(xhash_s *, uint8_t const *, unsigned int, void *, unsigned int)
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 10 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void *
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8),
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // xhash_s *()(void)
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 17 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 18 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
/* 19 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // xhash_s
};

static void _cffi_d_xhash_done(xhash_s * x0, uint8_t const * x1, unsigned int x2, void * x3, unsigned int x4)
{
  xhash_done(x0, x1, x2, x3, x4);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_xhash_done(PyObject *self, PyObject *args)
{
  xhash_s * x0;
  uint8_t const * x1;
  unsigned int x2;
  void * x3;
  unsigned int x4;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;

  if (!PyArg_UnpackTuple(args, "xhash_done", 5, 5, &arg0, &arg1, &arg2, &arg3, &arg4))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (xhash_s *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (uint8_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, unsigned int);
  if (x2 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(12), arg3, (char **)&x3);
  if (datasize != 0) {
    x3 = ((size_t)datasize) <= 640 ? (void *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(12), arg3, (char **)&x3,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x4 = _cffi_to_c_int(arg4, unsigned int);
  if (x4 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { xhash_done(x0, x1, x2, x3, x4); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_xhash_done _cffi_d_xhash_done
#endif

static void _cffi_d_xhash_free(xhash_s * x0)
{
  xhash_free(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_xhash_free(PyObject *self, PyObject *arg0)
{
  xhash_s * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (xhash_s *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { xhash_free(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_xhash_free _cffi_d_xhash_free
#endif

static void _cffi_d_xhash_iter(xhash_s * x0, uint8_t const * x1, unsigned int x2)
{
  xhash_iter(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_xhash_iter(PyObject *self, PyObject *args)
{
  xhash_s * x0;
  uint8_t const * x1;
  unsigned int x2;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "xhash_iter", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (xhash_s *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(1), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    x1 = ((size_t)datasize) <= 640 ? (uint8_t const *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg1, (char **)&x1,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, unsigned int);
  if (x2 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { xhash_iter(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_xhash_iter _cffi_d_xhash_iter
#endif

static xhash_s * _cffi_d_xhash_new(void)
{
  return xhash_new();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_xhash_new(PyObject *self, PyObject *noarg)
{
  xhash_s * result;
  PyObject *pyresult;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = xhash_new(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  pyresult = _cffi_from_c_pointer((char *)result, _cffi_type(1));
  return pyresult;
}
#else
#  define _cffi_f_xhash_new _cffi_d_xhash_new
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "xhash_done", (void *)_cffi_f_xhash_done, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 8), (void *)_cffi_d_xhash_done },
  { "xhash_free", (void *)_cffi_f_xhash_free, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_xhash_free },
  { "xhash_iter", (void *)_cffi_f_xhash_iter, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d_xhash_iter },
  { "xhash_new", (void *)_cffi_f_xhash_new, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 15), (void *)_cffi_d_xhash_new },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "xhash_s", 19, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "u8", 17 },
  { "uint", 6 },
  { "xhash_s", 19 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  4,  /* num_globals */
  1,  /* num_struct_unions */
  0,  /* num_enums */
  3,  /* num_typenames */
  NULL,  /* no includes */
  20,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_xstorelib(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_xstorelib(void) { return NULL; }
#  else
     initxstorelib(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_xstorelib(void)
{
  return _cffi_init("xstorelib", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initxstorelib(void)
{
  _cffi_init("xstorelib", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
